import {defineStore} from 'pinia'
import {ref} from "vue";

export const useSeatList = defineStore('seatList', () => {
    const seat_list = ref([
        {
            name: '欧阳娜',
            id: '1',
            sex: '男'
        }, {
            name: '欧阳娜',
            id: '1',
            sex: '男'
        }, {
            name: '欧阳娜',
            id: '1',
            sex: '女'
        }, {
            name: '站三分',
            id: '1',
            sex: '男'
        }, {
            name: '菠萝啤',
            id: '1',
            sex: '女'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三99',
            id: '1',
            sex: '男'
        }
    ])

    return {
        seat_list,
    }
})