import {defineStore} from 'pinia'
import {ref} from "vue";

export const useStuList = defineStore('stuLists', () => {
    const stu_list = ref([
        {
            name: '欧阳娜',
            id: '0',
            sex: '男'
        },
        {
            name: '欧阳娜',
            id: '1',
            sex: '男'
        }, {
            name: '欧阳娜',
            id: '2',
            sex: '男'
        }, {
            name: '欧阳娜',
            id: '3',
            sex: '女'
        }, {
            name: '站三分',
            id: '4',
            sex: '男'
        }, {
            name: '菠萝啤',
            id: '5',
            sex: '女'
        }, {
            name: '张三5',
            id: '6',
            sex: '男'
        }, {
            name: '张三5',
            id: '7',
            sex: '男'
        }, {
            name: '张三5',
            id: '8',
            sex: '男'
        }, {
            name: '张三5',
            id: '9',
            sex: '男'
        }, {
            name: '张三5',
            id: '10',
            sex: '男'
        }, {
            name: '张三5',
            id: '11',
            sex: '男'
        }, {
            name: '张三5',
            id: '12',
            sex: '男'
        }, {
            name: '张三5',
            id: '13',
            sex: '男'
        }, {
            name: '张三5',
            id: '14',
            sex: '男'
        }, {
            name: '张三5',
            id: '15',
            sex: '男'
        }, {
            name: '张三5',
            id: '16',
            sex: '男'
        }, {
            name: '张三5',
            id: '17',
            sex: '男'
        }, {
            name: '张三5',
            id: '18',
            sex: '男'
        }, {
            name: '张三5',
            id: '19',
            sex: '男'
        }, {
            name: '张三5',
            id: '20',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三5',
            id: '1',
            sex: '男'
        }, {
            name: '张三99',
            id: '1',
            sex: '男'
        }
    ])

    return {
        stu_list,
    }
})